# Project identification
sonar.projectKey=TODOLIST
sonar.projectName=TODOLIST
sonar.projectVersion=1.1

# Source directories
sonar.sources=src,js,scripts
sonar.tests=test,specs,__tests__

# Language
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.login=sqp_28870cc8e37381a4d8dbdeff8166d0c2c50cbe5f

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/vendor/**,**/*.min.js,**/coverage/**,**/libs/**
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/build/**