# Project identification
sonar.projectKey=TODOLIST 
sonar.projectName=TODOLIST 
sonar.projectVersion=1.1 

# Source directory
sonar.sources=.

# Language
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8

# SonarQube server URL
sonar.host.url=http://localhost:9000

# Authentication Token
sonar.login=sqp_28870cc8e37381a4d8dbdeff8166d0c2c50cbe5f

