# Project identification
sonar.projectKey=TODOLIST
sonar.projectName=TODOLIST
sonar.projectVersion=1.2

# Source directories
sonar.sources=.
# sonar.tests=tests

# Language
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.login=sqp_a9c1bfd06939936699a14f261a0e624d14710f16

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/vendor/**,**/*.min.js,**/coverage/**,**/libs/**
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/build/**